### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 10ko** [10ko/boxedjs#5]
### This is an unofficial and (sort-of) ordered roadmap/todo for the project features.
This doesn't include regular refactoring, tests, etc.

 - [x] ~~Introduce the concept of "content". Specify a file format for declaring text and images to be applied to templates/pages.~~ IMPLEMENTED
- [x] Create example folders (especially important after the previous step). IMPLEMENTED
- [ ] Add SASS support
- [ ] Add express server to serve/preview website
- [ ] Add autoreload
- [ ] Remove documentation from README.md to it's own section (Add contributing guide/usage guide).
- [ ] Make a github.io page to present project (???)

Open questions:
- ~~Recursion and templates: not supported in first versions, investigation needed for future implementations.~~ IMPLEMENTED
- ~~Investigate how to store the content: yml, json, md or something else.~~ yml/yaml/json IMPLEMENTED
- Would it help to bundle everything in a mac app?
- Functionality to publish to github pages?
